### ISSUE TITLE
No matches for aoc_helper[cli]

### ISSUE THREAD

**Issue by thomasaarholt** [Starwort/aoc_helper#6]
I've run

`pip install aoc_helper`, then ran `python -m aoc_helper` to enter the session token. That returned:
`Missing dependencies for the CLI. Please pip install aoc_helper[cli]`, so I ran `pip install aoc_helper[cli]`, and that returned `zsh: no matches found: aoc_helper[cli]`.

This is on Mac, checked with python 3.9 and 3.10.

**Comment by Starwort** [comment]
Given that the error returned begins with `zsh:`, I believe this is a zsh issue; can you try: a) using quotes around `aoc_helper[cli]` (`pip install "aoc_helper[cli]"`) or b) running the command with bash? It would seem weird that this is broken for only `aoc_helper` because that's the standard way of installing optional dependencies for Python modules

**Comment by thomasaarholt** [comment]
Not sure how I blanked on that probably being the problem, although the error message isn't exactly verbose.

This seems to be zsh or pip related issue indeed! I've tried with a different package, and get the exact same error with `pip install hyperspy[all]`
